## Config

# Data paths
statement_dir: "C:/Users/pcharbonnier/OneDrive - DVHE/Etudes/ENSAE 2025-2026/Cours/ML for trading/data/Statements"
pressconf_dir: "C:/Users/pcharbonnier/OneDrive - DVHE/Etudes/ENSAE 2025-2026/Cours/ML for trading/data/Q&A"
sentiment_cache: "C:/Users/pcharbonnier/OneDrive - DVHE/Etudes/ENSAE 2025-2026/Cours/ML for trading/data/sentiment/sentiment_cache.csv"

# File regex format
statement_regex: "(?i)monetary(\\d{8})a1\\.pdf$"
pressconf_regex: "(?i)FOMCpresconf(\\d{8})\\.pdf$"
date_fmt: "%Y%m%d"

# LLM / Chunker
model: "gtfintechlab/FOMC-RoBERTa"
max_tokens: 510
stride: 96

# Threading
max_workers: 4

# Output
output_path: "out/fed_scores.csv"

# Date details
fomc_time : "14:00:00"
qa_time : "14:30:00"